### ISSUE TITLE
Question: Referencing "http://purl.archive.org/language-data-commons/context.json" in the context

### ISSUE THREAD

**Issue by marcolarosa** [Language-Research-Technology/ldac-profile#4]
I'm going through the validator and updating the paradisec exporter and I'm not sure what to do about this issue. When I flatten or compact the crate with the following context I get an error:

```
[
        "https://w3id.org/ro/crate/1.1/context",
        "http://purl.archive.org/language-data-commons/context.json",
        {
            "@vocab": "http://schema.org/",
        },
        {
            "@base": null,
        },
    ]
```

And the error is:

```
jsonld.InvalidUrl: Dereferencing a URL did not result in a JSON object. The response was valid JSON, but it was not a JSON object.
    at ContextResolver._fetchContext (/Users/mlarosa/src/pdsc/nabu-exporter/node_modules/jsonld/lib/ContextResolver.js:186:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async ContextResolver._resolveRemoteContext (/Users/mlarosa/src/pdsc/nabu-exporter/node_modules/jsonld/lib/ContextResolver.js:117:34)
    at async ContextResolver.resolve (/Users/mlarosa/src/pdsc/nabu-exporter/node_modules/jsonld/lib/ContextResolver.js:50:22)
    at async api.process (/Users/mlarosa/src/pdsc/nabu-exporter/node_modules/jsonld/lib/context.js:87:20)
    at async api.expand (/Users/mlarosa/src/pdsc/nabu-exporter/node_modules/jsonld/lib/expand.js:214:17)
    at async Function.jsonld.expand (/Users/mlarosa/src/pdsc/nabu-exporter/node_modules/jsonld/lib/jsonld.js:321:18)
    at async Function.jsonld.compact (/Users/mlarosa/src/pdsc/nabu-exporter/node_modules/jsonld/lib/jsonld.js:171:16)
    at async exportItem (/Users/mlarosa/src/pdsc/nabu-exporter/src/tools/export.js:100:17)
    at async /Users/mlarosa/src/pdsc/nabu-exporter/src/tools/export.js:57:9 {
  details: {
    code: 'invalid remote context',
    url: 'http://purl.archive.org/language-data-commons/context.json'
  }
}

```

Looking at the browser console the response header content-type is "text/html".
![Screenshot 2022-12-07 at 1 19 04 pm](https://user-images.githubusercontent.com/2639995/206071993-2e51361f-5534-4989-a3f6-51295333fa1e.png)

If I do the same with the ro crate context the content-type is "application/ld+json"
![Screenshot 2022-12-07 at 1 19 08 pm](https://user-images.githubusercontent.com/2639995/206072073-2ff59abd-a4ed-40f0-8c44-d9e19e30176a.png)

**Comment by ptsefton** [comment]
I don't know an immediate solution for this - will need to look into where we can host the file so the MIME type is correct (@alvinsw any ideas?). If you are using the RO-Crate library you could update it and use the latest - it doesn't use that flatten algorithm.

**Comment by marcolarosa** [comment]
I've been rewriting the exporter to use the rocrate library and have raised some questions about that (and provided a [pull request](https://github.com/Arkisto-Platform/ro-crate-js/pull/6) to pretty print the docs).

That aside, whether I use flatten / compact or not, a solution needs to be found to this issue as it precludes using the standard json-ld tools.

**Comment by ptsefton** [comment]
Yes - absolutely we need to fix it.
