### ISSUE TITLE
Bug: this code is not handling the case when hasPart is empty or doesn't exist

### ISSUE THREAD

**Issue by marcolarosa** [Language-Research-Technology/ldac-profile#5]
https://github.com/Language-Research-Technology/ldac-profile/blob/e31fcce202f14f6390b8018f2b699637e30469f1/lib/rules.js#L346-L355

The rule is a should rule but when the `hasPart` doesn't exist or is an empty array the following incomprehensible error is thrown:

```
 TypeError: values is not iterable
      at Object.validate (lib/rules.js:355:20)
      at validateEntity (lib/validator.js:24:19)
      at Object.validate (lib/rules.js:90:7)
      at validateEntity (lib/validator.js:24:19)
      at Function.validate (lib/profile.js:19:12)
      at Context.<anonymous> (test/validator.paradisec.spec.js:114:30)
      at processImmediate (node:internal/timers:466:21)
```    

It probably needs something like `if (!values) report some warning` in line 354

**Comment by ptsefton** [comment]
Fixed it

----------------------------

Dr Peter Sefton
Senior Technical Advisor, School of Languages and Culture
Mobile: 0404 096 932

________________________________
From: Marco La Rosa ***@***.***>
Sent: Wednesday, December 7, 2022 15:23
To: Language-Research-Technology/ldac-profile ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [Language-Research-Technology/ldac-profile] Bug: this code is not handling the case when hasPart is empty or doesn't exist (Issue #5)


https://github.com/Language-Research-Technology/ldac-profile/blob/e31fcce202f14f6390b8018f2b699637e30469f1/lib/rules.js#L346-L355

The rule is a should rule but when the hasPart doesn't exist or is an empty array the following incomprehensible error is thrown:

 TypeError: values is not iterable
      at Object.validate (lib/rules.js:355:20)
      at validateEntity (lib/validator.js:24:19)
      at Object.validate (lib/rules.js:90:7)
      at validateEntity (lib/validator.js:24:19)
      at Function.validate (lib/profile.js:19:12)
      at Context.<anonymous> (test/validator.paradisec.spec.js:114:30)
      at processImmediate (node:internal/timers:466:21)


It probably needs something like if (!values) report some warning in line 354
